name: RSpec

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.5.x
          - 2.6.x
          - 2.7.x
          - 3.0.x
        gemfile:
          - gemfiles/rails_5.2.gemfile
          - gemfiles/rails_6.0.gemfile
          - gemfiles/rails_6.1.gemfile
        exclude:
          - gemfile: gemfiles/rails_5.2.gemfile
            ruby: 3.0.x
    env:
      BUNDLE_GEMFILE: ${{ format('{0}/{1}', github.workspace, matrix.gemfile) }}
      BUNDLE_PATH: ${{ format('{0}/vendor/bundle', github.workspace) }}
      BUNDLE_DEPLOYMENT: true
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install Bundler
        run: gem install bundler:2.2.14
      - name: Cache Bundler
        uses: actions/cache@v1
        id: cache-bundler
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ matrix.ruby }}-${{ hashFiles(format('{0}/{1}.lock', github.workspace, matrix.gemfile)) }}
          restore-keys: |
            ${{ runner.os }}-gem-${{ matrix.ruby }}-
      - name: Install Bundler dependencies
        if: steps.cache-bundler.outputs.cache-hit != 'true'
        run: bundle install --jobs=4
      - name: Check Bunlder dependencies
        run: bundle check
      - name: RSpec
        run: bundle exec rspec
